import React from "react";
import { ReactNode } from "react";
import Head from "next/head";
import Navbar from "@/../components/Navbar";

export default function BaseLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="container-fluid">
        {children}
      </div>
    </>
  );
}
